---

- name: Converge
  hosts: all
  gather_facts: no
  tasks:
    - name: "Include ckaserer.authorized_keys"
      include_role:
        name: "ansible-role-authorized-keys"
      vars:
        authorization_list:
          - name: root
            ssh_keys:
              - john-doe
              - jane-doe
          - name: waldo
            ssh_keys:
              - john-doe
              - jane-doe
        create_backup: true
        exclusive_authorized_keys: true
        fail_when_user_not_found: false
        select_public_keys_from_path: "molecule/resources/public-keys"

...
