---

dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-06
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy
    - syntax
    - lint
    - create
    - prepare
    - converge
    - side_effect
    - converge
    - idempotence
    - verify
    - destroy
lint: |
  set -e
  ansible-lint .

...
