---

- name: Converge
  hosts: all
  gather_facts: no
  tasks:
    - name: Include ckaserer.authorized_key
      include_role:
        name: ansible-role-authorized-keys
      vars:
        authorization_list:
          - name: root
            ssh_keys:
              - john-doe
        select_public_keys_from_path: molecule/resources/public-keys

...
