---

dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-00
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  ansible-lint .

...
