---
- name: Converge
  hosts: all
  gather_facts: no
  tasks:
  
    - block:
        - name: "Restore authorized_keys from specific Backup"
          include_role:
            name: "ckaserer.authorized_keys"
          vars:
            authorization_list:
              - name: root
              - name: donald-blake
              - name: waldo
            restore_authorized_keys: true
            fail_when_user_not_found: true
            restore_authorized_keys_from_file: "~/.ssh/authorized_keys.bak"
          register: expected_failure

        - name: "Check execution halted"
          fail:
            msg: "Execution should stop before this task"
          register: should_not_run
  
      rescue:
        - assert:
            that:
              - expected_failure is defined
              - should_not_run is not defined
...
