---
- name: Converge
  hosts: all
  gather_facts: no
  tasks:
    - name: Include ckaserer.authorized_keys
      include_role:
        name: ckaserer.authorized_keys
      vars:
        authorization_list:
          - name: root
            ssh_keys:
              - john-doe
              - jane-doe
          - name: donald-blake
            ssh_keys:
              - john-doe
              - jane-doe
          - name: waldo
            ssh_keys:
              - john-doe
              - jane-doe
        create_backup: false
        fail_when_user_not_found: false
        select_public_keys_from_path: molecule/resources/public-keys
...
