---
- name: Prepare
  hosts: all
  gather_facts: no
  tasks:

    - name: Add the user donald-blake
      user:
        name: donald-blake
        create_home: yes
        state: present

    - name: Set authorized_keys
      include_role:
        name: ckaserer.authorized_keys
      vars:
        authorization_list:
          - name: root
            ssh_keys:
              - john-doe
          - name: donald-blake
            ssh_keys:
              - john-doe
        create_backup: false
        exclusive_authorized_keys: true
        fail_when_user_not_found: false
        select_public_keys_from_path: molecule/resources/public-keys

    - name: Set additional authorized_keys and create a backup
      include_role:
        name: ckaserer.authorized_keys
      vars:
        authorization_list:
          - name: root
            ssh_keys:
              - jane-doe
              - john-doe
          - name: donald-blake
            ssh_keys:
              - john-doe
              - jane-doe
        create_backup: true
        exclusive_authorized_keys: true
        fail_when_user_not_found: false
        select_public_keys_from_path: molecule/resources/public-keys

    - name: Create custom backups
      copy: 
        remote_src: true
        src: "{{ item }}/authorized_keys"
        dest: "{{ item }}/authorized_keys.bak"
        mode: "0644"
      with_items:
      - /root/.ssh
      - /home/donald-blake/.ssh
...
